const TOKENS: string[] = [
  "1INCHPERP",
  "AAVEPERP",
  "ADAPERP",
  "ALGOPERP",
  "ALICEPERP",
  // "AMPLPERP",
  // "ASDPERP",
  // "ATLASPERP",
  // "ATOMPERP",
  // "AUDIOPERP",
  // "AVAXPERP",
  // "BADGERPERP",
  // "BNBPERP",
  // "BRZPERP",
  // "C98PERP",
  // "CAKEPERP",
  // "CELPERP",
  // "CLVPERP",
  // "DEFIPERP",
  // "DOGEPERP",
  // "FILPERP",
  // "FTTPERP",
  // "GRTPERP",
  // "LINKPERP",
  // "LUNAPERP",
  // "MERPERP",
  // "MNGOPERP",
  // "MNGOPERP",
  // "NEARPERP",
  // "PERPPERP",
  // "RAYPERP",
  // "REEFPERP",
  // "RUNEPERP",
  // "SANDPERP",
  // "SHIBPERP",
  // "SOLPERP",
  // "STEPPERP",
  // "SUSHIPERP",
  // "TRXPERP",
  // "UNIPERP",
  // "VETPERP",
  // "WAVESPERP",
  // "XLMPERP",
  // "XTZPERP"
]

export { TOKENS }
